#!/usr/bin/env bash

# Test for an interactive shell
[[ $- != *i* ]] && return

# Load shell configuration options
. "$(readlink -f $(dirname $(readlink -f $HOME/.bashrc))/../)/lib/loader"
#agent_auto
shells_auto

# Load the local config
[ -f "$HOME/.bashrc.local" ] && . "$HOME/.bashrc.local"
