#!/usr/bin/env bash
##       ________   ___       ___
##      /  _____/  /  /      /  /
##     /  /       /  /      /  /
##    /  /       /  /____  /  / _______  _______  ____  ____
##   /  /       /  ___  / /  / /  __  / /  ____/ /    \/    \
##  /  /_____  /  /  / / /  / /  /_/ / /  /     /  /\    /\  \
## /________/ /__/  /_/ /__/ /______/ /__/     /__/  \__/  \__\ TM
##
## Title: Local BashRC Configuration File
## Author: Cody Opel
## E-mail: codyopel(at)gmail.com
## Copyright (c) 2014 All Rights Reserved, http://www.chlorm.net
## License: The MIT License - http://opensource.org/licenses/MIT
## Comments:
##    Assumed Directory & File Structure:
##      ~/.bashrc
##    Legend:
##      () - option
##      [] - description
##      ## - comments [not to be uncommented]
##      # -- commented variables

## [http://en.wikipedia.org/wiki/Unicode_symbols]

# Load shell configuration options
. "$(readlink -f $(dirname $(readlink -f ~/.bashrc))/../)/lib/loader"
agent_auto
#shell_best $@
shell_init
shell_theme

## Test for an interactive shell.
if [[ $- != *i* ]] ; then
	## Shell is non-interactive.  Be done now!
	return
fi

export LANGUAGE="en_US:en"

## [ls colors]
#LS_COLORS='no=00:fi=00:di=01;35:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.7z=01;34:*.iso=01;34:*.tar=01;34:*.tgz=01;34:*.zip=01;34:*.gz=01;34:*.bz2=01;34:*.deb=01;34:*.rpm=01;34:*.jar=01;34:*.xz=01;34:*.jpg=01;33:*.jpeg=01;33:*.gif=01;33:*.bmp=01;33:*.tga=01;33:*.xbm=01;33:*.tif=01;35:*.tiff=01;33:*.png=01;33:*.avc=01;32:*.h264=01;32:*.h265=01;32:*.hevc=01;32:*.hvc=01;32:*.mkv=01;32:*.mov=01;32:*.mpg=01;32:*.mpeg=01;32:*.avi=01;32:*.flv=01;32:*.mp4=01;32:*.ape=01;31:*.flac=01;31:*.mp3=01;31:*.mpc=01;31:*.ogg=01;31:*.wav=01;31:';
#export LS_COLORS
## TODO: Create global color scheme and export variables

update () {
    sudo emerge --sync
    sudo emerge --ask --update --deep --with-bdeps=y --newuse --keep-going @world
}
## [list all packages from overlays with corresponding overlay name]
fromover () {
    for i in /var/db/pkg/*/*; do
        if ! grep gentoo $i/repository >/dev/null; then
            echo -e "`basename $i`\t`cat $i/repository`"
        fi
    done
}

# [color man pages]
## TODO: update color scheme to match global
man () {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}