#!/usr/bin/env zsh

[[ -o interactive ]] || return

setopt PROMPT_SUBST

if [[ -o login ]] ; then
  . "$(readlink -f $(dirname $(readlink -f $HOME/.zshrc))/../)/login-shell.sh"
fi

# Load shell configuration loader
. "$(readlink -f $(dirname $(readlink -f $HOME/.zshrc))/../)/loader.sh"

alias sudo="nocorrect sudo"

# Load the local config
if [ -f "$HOME/.zshrc.local" ] ; then
  . "$HOME/.zshrc.local"
fi
