#!/usr/bin/env zsh

# Load shell configuration options
source "$(readlink -f $(dirname $(readlink -f $HOME/.zshrc))/../)/lib/loader"
shells_auto

alias sudo="nocorrect sudo"

# Load the local config
[ -f "$HOME/.zshrc.local" ] && source $HOME/.zshrc.local
