#!/usr/bin/env sh

# Constants
TEST_PASS=0
TEST_SKIP=120

# Helpers
test_longest_str () {

  local MAX

  MAX="0"

  array_forall TESTS test_max
  echo "$MAX"

}

test_max () {

  [ "$MAX" -le "${#1}" ] && MAX="${#1}"

  return 0

}

test_register () { # Registering and running the test suite

  array_append TESTS "$1"

}

test_clear () { # Unregisters all tests

  array_new TESTS

}

test_run_ () { # Run a single test

  local TFILE

  TFILE="$(dir_tmp)/config_test_err"

  if [ "$(shell_nov)" = "dash" ] || [ "$(shell_nov)" = "sh" ] ; then
    printf "%${1}s  [Running]" "$2"
    (eval "$2") > "$TFILE" 2>&1
    case "$?" in

      $TEST_PASS)
        printf "\r%${1}s  [Passed] \n" "$2"
        ;;

      $TEST_SKIP)
        printf "\r%${1}s  [Skipped]\n" "$2"
        ;;

      *)
        printf "\r%${1}s  [Failed] \n" "$2"
        cat "$TFILE" 2> /dev/null
        echo ""
        ;;

    esac
  else
    printf "%${1}s  [$(shell_color yellow 0)Running$(shell_color reset 0)]" "$2"
    (eval "$2") > "$TFILE" 2>&1
    case "$?" in

      $TEST_PASS)
        printf "\r\e[K%${1}s  [$(shell_color green 0)Passed$(shell_color reset 0)]\n" "$2"
        ;;

      $TEST_SKIP)
        printf "\r\e[K%${1}s  [$(shell_color yellow 0)Skipped$(shell_color reset 0)]\n" "$2"
        ;;

      *)
        printf "\r\e[K%${1}s  [$(shell_color red 0)Failed$(shell_color reset 0)]\n" "$2"
        echo "Error output:"
        cat "$TFILE" 2> /dev/null
        echo ""
        ;;

    esac
  fi
  rm -f "$TFILE"
}

alias test_run='test_run_ 0'

test_run_all () { # Run all of the tests

  echo "$RUNNING_SHELL: Running Full Test Suite:"
  array_forall TESTS "test_run_ $(test_longest_str)"

}

# Test Helpers
test_seq () {

  [ "$1" != "$2" ] && {
    echo "Expected: $1"
    echo "Got: $2"
    exit 1
  }

}

test_sneq () {

  [ "$1" = "$2" ] && {
    echo "Expected: $1"
    echo "Got: $2"
    exit 1
  }

}

test_eq () {

  [ "$1" -ne "$2" ] && {
    echo "Expected: $1"
    echo "Got: $2"
    exit 1
  }

}

# Setup the testing environment
. "$(readlink -f $(dirname $(readlink -f $HOME/.xinitrc))/../)/lib/loader"
[ -z "$RUNNING_SHELL" ] && RUNNING_SHELL="$(shell)"
test_clear
