#!/usr/bin/env sh
. "$(readlink -f $(dirname $(readlink -f $HOME/.xinitrc))/../)/test/lib"
run_test () {
  export RUNNING_SHELL="$(basename "$(readlink -f "$(which "$1" 2>/dev/null)")")"
  if path_hasbin $1; then
    $1 $(dirname "$0")/test
    echo ""
  else
    echo "$1: Shell was not found"
    echo ""
  fi
}
run_test bash
run_test zsh
run_test dash
run_test sh
