#!/usr/bin/env sh

export DIR_CONF="$(readlink -f "$(dirname "$(readlink -f "$0")")")"

cd "$DIR_CONF"

if [ ! -f "settings.local" ] ; then
  touch "settings.local"
  echo '#!/usr/bin/env sh' >> "settings.local"
fi

# Load configuration settings
. "$DIR_CONF/settings"
. "$DIR_CONF/settings.local"

. lib/loader || exit 128

[ -z "$dotfilesRepo" ] && { echo "ERROR: dotfiles remote repo origin is not set" ; exit 1 ; }

git remote set-url origin "$dotfilesRepo"
git remote set-url --push origin "$dotfilesRepo"

echo "Updating Config Files"
config_latest
if [ "$?" -gt "1" ] ; then
  echo "Failed to update Config"
  exit 1
fi

echo "Installing Config Files"
if ! config_install ; then
  echo "Failed to Install Config"
  exit 1
fi
