#!/usr/bin/env sh

export DIR_CONF="$(readlink -f "$(dirname "$(readlink -f "$0")")")"

cd "$DIR_CONF"

[ -f "settings.local" ] || {
  touch "settings.local"
  echo '#!/usr/bin/env sh' >> "settings.local"
}

# Load configuration settings
. "$DIR_CONF/settings"
. "$DIR_CONF/settings.local"

. lib/loader || exit 128

[ -z "$dotfilesRepo" ] && { echo "ERROR: dotfiles remote repo origin is not set" ; exit 1 ; }

git remote set-url origin "$dotfilesRepo"
git remote set-url --push origin "$dotfilesRepo"

echo "Updating Config Files"
config_latest || { echo "Failed to update Configs" ; exit 1 ; }

config_install || { echo "ERROR: configuration install failed" ; exit 1 ; }
