#!/usr/bin/env sh

# Set dotfiles git repo remote origin
dotfilesRepo="https://github.com/codyopel/dotfiles.git"

# List hostname of all workstations
workStations='^\(NOS-4-A2\|LGM\|Shivkatall\)'

# Shells in order of preference
# Options: bash, dash, fish, sh, zsh (sh = system default)
shellPreference=(bash dash fish zsh sh)

# Desktop environments in order of preference
# Options: awesome, cinnamon2, gnome3, i3, kde4, kde5, xfce4, xmonad
dePreference=(xmonad cinnamon2 gnome3 i3 awesome xfce4 kde4)

# Trash directories
DIR_TRASH_INFO="$HOME/.local/share/Trash/info"
DIR_TRASH_FILES="$HOME/.local/share/Trash/files"

# TODO: Shell priority list

# TODO: Editor list