#!/usr/bin/env sh

EMAIL="codyopel@gmail.com"

# Set dotfiles git repo remote origin
dotfilesRepo="https://github.com/codyopel/dotfiles.git"

GIT_NAME="codyopel"
GIT_EMAIL="$EMAIL"

# List hostname of all workstations
workStations='^\(NOS-4-A2\|LGM\|Shivkatall\)'

# High DPI
HIGH_DPI=false

# Headless apps to configure
appsHeadless=(beets cabal emacs git golang gvim htop minidlna mpd ncmpcpp nixpkgs\
              pulseaudio rtorrent ssh tmux vim)

# Graphical apps to configure
appsGraphical=(sakura sublimetext suckless xorg)

# Desktop environments in order of preference [awesome,cinnamon,gnome,i3,kde,xfce,xmonad]
deskenvsPreference=(xmonad gnome kde)

# Shells in order of preference [ash,bash,csh,dash,fish,korn,pdksh,tcsh,zsh]
shellsPreference=(zsh bash fish)

# Text editors in order of preference [emacs,nano,vi,vim,yi]
editorPreference=(emacs vim nano)

# XDG directories
XDG_CACHE_HOME="$HOME/.cache"
XDG_CONFIG_HOME="$HOME/.config" # The config directory cannot be modified currently
XDG_DATA_HOME="$HOME/.local/share"
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_TEMPLATES_DIR="$HOME/.templates"
XDG_VIDEOS_DIR="$HOME/Videos"

# Trash directories
DIR_TRASH_INFO="$HOME/.local/share/Trash/info"
DIR_TRASH_FILES="$HOME/.local/share/Trash/files"
