#!/usr/bin/env sh

app_golang_installed () {

  path_hasbin "go" > /dev/null || return 1

  return 0

}

app_golang_dirs () {


  exist -dc "$HOME/.go/bin" "$HOME/.go/src" || return 1

  return 0

}

app_golang_paths () {

  export GOPATH="$HOME/.go" || return 1

  path_add "$PATH:$HOME/.go/bin" || return 1

  return 0

}

app_golang_cleanup () {

  exist -dx "$HOME/.go"

}

app_golang_configure () {

  app_golang_installed || return 2

  app_golang_dirs || return 1

  app_golang_paths || return 1

  return 0

}
