#!/usr/bin/env sh

app_gvim_installed () {

  path_hasbin "gvim" > /dev/null || return 1

  return 0

}

app_gvim_dotfiles () {

  exist -fx "$HOME/,gvimrc"

  config_ln "gvimrc" || return 1

  return 0

}

app_gvim_cleanup () {

  exist -fx "$HOME/.gvimrc"

}

app_gvim_configure () {

  app_gvim_installed || return 2

  app_gvim_dotfiles || return 1

  return 0

}
