#!/usr/bin/env sh

app_vim_installed() {

  path_hasbin "nvim" > /dev/null || return 1

  return 0

}

app_vim_dotfiles() {

  dotfile_ln "nvim" || return 1
  dotfile_ln "nvimrc" || return 1

  return 0

}

app_vim_cleanup() {

  exist -dx "$HOME/.nvim"
  exist -fx "$HOME/.nvimrc"

}

app_vim_configure() {

  app_vim_installed || return 2

  exist -dx "$HOME/.nviminfo" || return 1

  app_vim_dotfiles || return 1

  return 0

}
