#!/usr/bin/env sh

app_pulseaudio_installed() {

  path_hasbin "pacmd" > /dev/null || return 1

  return 0

}

app_pulseaudio_dirs() {

  exist -dc "$XDG_CONFIG_HOME/pulse" || return 1

  return 0

}

app_pulseaudio_dotfiles() {

  exist -fx "$XDG_CONFIG_HOME/pulse/daemon.conf"

(
cat <<PULSEAUDIO
default-sample-format = s24le
default-sample-rate = 192000
resample-method = speex-float-5

PULSEAUDIO
) > "$XDG_CONFIG_HOME/pulse/daemon.conf" || return 1

  return 0

}

app_pulseaudio_cleanup() {

  exist -dx "$XDG_CONFIG_HOME/pulse"

}

app_pulseaudio_configure() {

  app_pulseaudio_installed || return 2

  app_pulseaudio_dirs || return 1

  app_pulseaudio_dotfiles || return 1

  return 0

}
