#!/usr/bin/env sh

app_sakura_installed() {

  path_hasbin "sakura" > /dev/null || return 1

  return 0

}

app_sakura_dirs() {

  exist -dc "$XDG_CONFIG_HOME/sakura" || return 1

  return 0

}

app_sakura_dotfiles() {
 
  dotfile_ln "config/sakura" || return 1

}

app_sakura_cleanup() {

  exist -dx "$XDG_CONFIG_HOME/sakura"

}

app_sakura_configure() {

  app_sakura_installed || return 2

  app_sakura_dirs || return 1

  app_sakura_dotfiles || return 1

  return 0

}
