#!/usr/bin/env sh

# Application specific configuration

apps_configure() {

  local APP
  local APPS

  # Use environment variable $DISPLAY to determine if session is graphical
  if [ -n "$DISPLAY" ] ; then
    APPS=(${appsHeadless[@]} ${appsGraphical[@]})
  else
    APPS=(${appsHeadless[@]})
  fi

  for APP in ${APPS[@]} ; do
    if eval app_${APP}_configure ; then
      echo "  ☑ $APP"
    else
      if [ "$?" -ne "0" ] ; then
        if [ "$?" -eq "2" ] ; then
          echo "  ☐ $APP"
        elif [ "$?" -eq "1" ] ; then
          echo "  ☒ $APP"
        fi
      fi
      eval app_${APP}_cleanup
      continue
    fi
  done

  return 0

}
