#!/usr/bin/env sh

# Application specific configuration

apps_headless () {

  local APP

  for APP in ${appsHeadless[@]} ; do

    eval app_${APP}_configure || {

      [ "$?" -eq "2" ] && { echo "  ☐ $APP" ; }
      [ "$?" -eq "1" ] && { echo "  ☒ $APP" ; }

      eval app_${APP}_cleanup

      continue

    }

    echo "  ☑ $APP"

  done

  return 0

}

apps_graphical () {

  local APP

  for APP in ${appsGraphical[@]} ; do

    eval app_${APP}_configure || {

      [ "$?" -eq "2" ] && { echo "  ☐ $APP" ; }
      [ "$?" -eq "1" ] && { echo "  ☒ $APP" ; }

      eval app_${APP}_cleanup

      continue

    }

    echo "  ☑ $APP"

  done

  return 0

}

apps_configure () {

  apps_headless

  [ app_xorg_installed ] && {
    apps_graphical
  }

}
