#!/usr/bin/env sh

pulseaudio_path () {

  # Make sure pulseaudio is installed
  path_hasbin pacmd || return 1

  return 0

}

pulseaudio_configure () {

  # if pulseaudio isn't installed, be done now
  pulseaudio_path || return 1

  if [ ! -d "$HOME/.config/pulse" ] ; then
    mkdir -p "$HOME/.config/pulse"
  fi

  config_ln "config/pulse/daemon.conf"

}

audio_auto () {

  pulseaudio_configure

}