#!/usr/bin/env sh

pulseaudio_audio () {

  # If pulseaudio isn't installed, be done now
  path_hasbin pacmd || return 1

  dir_exist "$HOME/.config/pulse" || return 1

  config_ln "config/pulse/daemon.conf"

}

audio_auto () {

  pulseaudio_audio

}