#!/usr/bin/env sh

# Start an application at login (not intended for graphical apps)
auto_start () {
  startApp="$@"
  # Make sure application is installed before continuing
  path_hasbin ${1} || { echo "WARNING: '${1}' is not installed"; return 1; }

  # Check to see if process is already started
  startAppPID=$(pgrep ${1})

  # If application is already running, no need to start it
  if [ -z "$startAppPID" ]; then
    ${startApp} &>/dev/null # || { echo "WARNING: 'mpd' failed to start"; return 1; }
  fi

  # Prevent terminal from defaulting to /nix/store
  cd $HOME

  return 0
}