#!/usr/bin/env sh

comp_sleep() { # Sleeps the computer

  comp_lock || return 1
  systemctl suspend >&2 && return 0
  suspend >&2 && return 0
  pm-suspend >&2 && return 0

}

comp_off() { # Powers off the computer

  sudo_wrap poweroff

}

comp_lock() { # Locks the screen

  path_hasbin slock && {
    run_quiet slock &
    return 0
  }

  run_quiet gnome-screensaver-command -l && return 0
  run_quiet xscreensaver-command -lock && return 0

  echo "Failed to lock the screen" >&2
  return 1

}
