#!/usr/bin/env sh

deskenvs_configure () { # Install DE configs

  deskenv_awesome
  deskenv_cinnamon
  deskenv_gnome
  deskenv_i3
  deskenv_kde
  deskenv_xfce
  deskenv_xmonad

  # clean this up later
  install -d $XDG_CONFIG_HOME
  config_ln "config/Terminal" "config/wallpaper" "config/uzbl"

}

deskenvs_executable () {

  case "$1" in

    'awesome')
      echo "awesome" && return 0
      ;;

    'cinnamon')
      echo "cinnamon-session" && return 0
      ;;

    'gnome')
      echo "gnome-session" && return 0
      ;;

    'i3')
      echo "i3" && return 0
      ;;

    'kde')
      echo "startkde" && return 0
      ;;

    'xfce')
      echo "startxfce4" && return 0
      ;;

    'xmonad')
      echo "xmonad" && return 0
      ;;

  esac

  return 1

}

deskenvs_preference () {

  local DE

  for DE in ${dePreference[@]} ; do

    path_hasbin "$(deskenvs_executable)" >/dev/null 2>&1 && { echo "$DE" ; return 0 ; }

  done

  return 1

}

deskenvs_startapps () { # Run background applications

  #run_quiet xbacklight -set 30 > /dev/null
  #run_quiet autocutsel -fork > /dev/null
  #run_quiet pulseaudio --start > /dev/null
  #run_quiet xscreensaver -no-splash & > /dev/null
  #run_quiet notbit -p 8445 -d > /dev/null
  #run_quiet VBoxClient-all > /dev/null
  #run_quiet xcompmgr > /dev/null
  #run_quiet setxkbmap -option ctrl:nocaps
  #[ -f "$HOME/.xinitrc.start" ] && . "$HOME/.xinitrc.start"
  #[ -f "$HOME/.xinitrc.end" ] && . "$HOME/.xinitrc.end"

}

deskenvs_terminal () {

  local HCFG
  local TERMRC
  local TILING
  local WM
  local WM_EXE

  WM="$(deskenvs_preference)"
  WM_EXE="$(deskenvs_executable "$WM")"
  TILING=0


  # Tiling WM
  case ${WM} in

    'awesome'|'i3'|'xmonad')
      TILING=1
      ;;

  esac

  TERMRC="$DOTFILES_DIR/dotfiles/config/Terminal/terminalrc"

  if [ "${TILING}" -eq "1" ] ; then
    HCFG="${TERMRC}.tiling.$(hostname)"
    if [ -f "${HCFG}" ] ; then
      symlink "${HCFG}" "${TERMRC}"
    else
      symlink "${TERMRC}.tiling" "${TERMRC}"
    fi
  else
    HCFG="${TERMRC}.window.$(hostname)"
    if [ -f "${HCFG}" ] ; then
      symlink "${HCFG}" "${TERMRC}"
    else
      symlink "${TERMRC}.window" "${TERMRC}"
    fi
  fi

}

deskenvs_run () { # Run the prefered window manager

  [ -z "$(deskenvs_preference)" ] && { return 1 ; }

  local PID
  local WM
  local WM_EXE

  WM="$(deskenvs_preference)"
  WM_EXE="$(deskenvs_executable "$WM")"
  PID=$(pgrep $WM_EXE)

  [ -z "$PID" ] && exec "$WM_EXE"

  return 0

}

deskenvs_auto () {

  deskenv_run
  deskenvs_terminal
  deskenvs_startapps

}
