#!/usr/bin/env sh

git_dev () {

  config_ln "gitconfig"

}

golang_dev () {

  path_hasbin go || return 1

  dir_exist "$HOME/.go/src" || return 1 

}

nixpkgs_dev () {

  path_hasbin nix-env || return 1

  config_ln "nixpkgs"

}

# Prepares the files needed for development
dev_auto () {

  git_dev
  golang_dev
  nixpkgs_dev

}