#!/usr/bin/env sh

# Prepares the files needed for development
dev_auto () {

  mkdir -p "$HOME/.go/src" >/dev/null 2>&1

  # Git config
  config_ln gitconfig

  # Nix package manager config
  config_ln "nixpkgs"

}