#!/usr/bin/env sh

xdg_dirs() {

  exist -dc "$XDG_CONFIG_HOME"

  exist -fx "$XDG_CONFIG_HOME/user-dirs.dirs"

(cat <<XDGUSERDIRS
XDG_CACHE_HOME="$XDG_CACHE_HOME"
XDG_CONFIG_HOME="$XDG_CONFIG_HOME"
XDG_DATA_HOME="$XDG_DATA_HOME"
XDG_DESKTOP_DIR="$XDG_DESKTOP_DIR"
XDG_DOCUMENTS_DIR="$XDG_DOCUMENTS_DIR"
XDG_DOWNLOAD_DIR="$XDG_DOWNLOAD_DIR"
XDG_MUSIC_DIR="$XDG_MUSIC_DIR"
XDG_PICTURES_DIR="$XDG_PICTURES_DIR"
XDG_PUBLICSHARE_DIR="$XDG_PUBLICSHARE_DIR"
XDG_TEMPLATES_DIR="$XDG_TEMPLATES_DIR"
XDG_VIDEOS_DIR="$XDG_VIDEOS_DIR"

XDGUSERDIRS
) > "$XDG_CONFIG_HOME/user-dirs.dirs"

  exist -dc "$XDG_CACHE_HOME" && export XDG_CACHE_HOME
  exist -dc "$XDG_CONFIG_HOME" && export XDG_CONFIG_HOME
  exist -dc "$XDG_DATA_HOME" && export XDG_DATA_HOME
  exist -dc "$XDG_DESKTOP_DIR" && export XDG_DESKTOP_DIR
  exist -dc "$XDG_DOCUMENTS_DIR" && export XDG_DOCUMENTS_DIR
  exist -dc "$XDG_DOWNLOAD_DIR" && export XDG_DOWNLOAD_DIR
  exist -dc "$XDG_MUSIC_DIR" && export XDG_MUSIC_DIR
  exist -dc "$XDG_PICTURES_DIR" && export XDG_PICTURES_DIR
  exist -dc "$XDG_PUBLICSHARE_DIR" && export XDG_PUBLICSHARE_DIR
  exist -dc "$XDG_TEMPLATES_DIR" && export XDG_TEMPLATES_DIR
  exist -dc "$XDG_VIDEOS_DIR" && export XDG_VIDEOS_DIR

  return 0

}

custom_dirs() {

  exist -dx "$HOME/dev"

}

configure_dirs() {

  xdg_dirs
  custom_dirs

}
