#!/usr/bin/env sh

# Determine which window manager is best suited
graphical_bestwm () {
  path_hasbin "xmonad" && { echo "xmonad"; return 0; }
  path_hasbin "awesome" && { echo "awesome"; return 0; }
  path_hasbin "startxfce4" && { echo "startxfce4"; return 0; }
  return 1
}

# Run the window manager with the best side apps
graphical_runwm () {
  # Determine the type of WM
  WM="$1"
  TILING=0

  # Run background applications
  run_quiet xbacklight -set 30
  run_quiet autocutsel -fork
  run_quiet pulseaudio --start
  run_quiet xscreensaver -no-splash &
  run_quiet notbit -p 8445 -d
  run_quiet VBoxClient-all
  run_quiet xcompmgr
  run_quiet setxkbmap -option ctrl:nocaps
  [ -f "$HOME/.xinitrc.start" ] && . "$HOME/.xinitrc.start"

  # Do specific WM init
  if [ "$WM" = "awesome" ]; then
    TILING=1
    if [ -d "$HOME/.config/wallpaper" ]; then
      if [ "$(ls "$HOME/.config/wallpaper" | wc -l)" -gt "1" ]; then
	    sleep 2
	    while true; do
		  awsetbg -r "$HOME/.config/wallpaper"
		  sleep 300
	    done &
	  fi
    fi
  elif [ "$WM" = "xmonad" ]; then
    TILING=1
    run_quiet hhp &
  fi

  # Configure applications
  local TERMRC
  TERMRC="$(dir_conf)/conf/config/Terminal/terminalrc"
  if [ "$TILING" -eq "1" ]; then
    HCFG="${TERMRC}.tiling.$(hostname -s)"
    if [ -f "$HCFG" ]; then
      symlink "$HCFG" "$TERMRC"
    else
      symlink "${TERMRC}.tiling" "$TERMRC"
    fi
  else
    HCFG="${TERMRC}.window.$(hostname -s)"
    if [ -f "$HCFG" ]; then
      symlink "${HCFG}" "$TERMRC"
    else
      symlink "${TERMRC}.window" "$TERMRC"
    fi
  fi

  # Start the window manager
  exec $@

  # Kill the rest of the processes
  [ -f "$HOME/.xinitrc.end" ] && . "$HOME/.xinitrc.end"
  run_quiet pulseaudio --kill
}

# Automatically pick a window manager to run
graphical_autorun () {
  local WM
  if [ "$#" -ge "1" ]; then
    WM="$(echo "$1" | tr '[A-Z]' '[a-z]')"
    [ "$WM" = "awesomewm" ] && WM="awesome"
    [ "$WM" = "xfce4" ] && WM="startxfce4"
    path_hasbin "$WM" || WM=""
  fi
  [ -z "$WM" ] && WM="$(graphical_bestwm)"

  graphical_runwm $WM
}

graphical_st () {(
  cd "$(dir_conf)/conf/nixpkgs/st/"
  if [ -f "config.$(hostname -s).h" ]; then
    symlink "config.$(hostname -s).h" "config.mach.h"
  else
    symlink "config.other.h" "config.mach.h"
  fi
)}

# Automatically Configures the graphical interface
graphical_auto () {
  install -d $HOME/.config
  rm -f $HOME/.Xdefaults $HOME/.config/sakura
  config_ln xinitrc xsession xmonad config/awesome config/Terminal config/wallpaper config/uzbl
  symlink "$HOME/.config/Terminal" "$HOME/.config/xfce4/terminal"
  graphical_st
  return 0
}
