#!/usr/bin/env sh

## TODO: Using a standard hostname format and parse to determine machines features

info_ws () { # Determine if this is a workstation

  [ "$WS" = "0" ] && return 0

  hostname | grep -q "$workStations"

}

info_root () { # Determine if the user is root

  [ "$(id -u)" -eq 0 ]

}
