#!/usr/bin/env sh

## TODO: Using a standard hostname format and parse to determine machines features

# Determine if this is a workstation
info_ws () {
  [ "$WS" = "0" ] && return 0
  [ "$(uname -n | grep -e "$workStations")" != "" ]
}

# Determine if the user is root
info_root () {
  [ "$(id -u)" -eq 0 ]
}