#!/usr/bin/env sh

# Use acpi if possible
laptop_bat () {
  acpi -b 2>/dev/null || laptop_bat_old
}

# Gets the string representing the state of the batteries
laptop_bat_old () {
  local BATS; local BAT_DIR
  [ -d "$ROOT/sys/class/power_supply" ] || return 1
  array_from_str BATS "$(ls "$ROOT/sys/class/power_supply" | grep "^BAT")"
  array_forall BATS laptop_bat_one
}
laptop_bat_one () {
  local BAT_DIR; local B; local NOW; local FULL;
  echo -n "$1: "
  BAT_DIR="$ROOT/sys/class/power_supply/$1"
  B="$(cat "$BAT_DIR/status" 2>/dev/null)" || return 1
  case "$B" in
    Charging)
      echo -n "↑"
      ;;
    Discharging)
      echo -n "↓"
      ;;
    *)
      echo -n "⚡"
  esac
  NOW="$(cat "$BAT_DIR"/charge_now 2>/dev/null || cat "$BAT_DIR"/energy_now 2>/dev/null || echo -1)"
  FULL="$(cat "$BAT_DIR"/charge_full 2>/dev/null || cat "$BAT_DIR"/energy_full 2>/dev/null || echo 1)"
  echo "$(expr $NOW \* 100 / $FULL)%"
}
