#!/usr/bin/env sh

# Create all necessary session files for mpd if they don't exist already
mpdSessionFiles () {
	if [ ! -f "$HOME/.config/mpd/database" ]; then
		touch "$HOME/.config/mpd/database"
	fi
	if [ ! -f "$HOME/.config/mpd/pid" ]; then
		touch "$HOME/.config/mpd/pid"
	fi
	if [ ! -f "$HOME/.config/mpd/state" ]; then
		touch "$HOME/.config/mpd/state"
	fi
	if [ ! -f "$HOME/.config/mpd/sticker.sql" ]; then
		touch "$HOME/.config/mpd/sticker.sql"
	fi
	if [ ! -f "$HOME/.config/mpd/log" ]; then
		touch "$HOME/.config/mpd/log"
	fi
	# FIFO output file for ncmpcpp visualizer
	if [ ! -f "$HOME/.config/mpd/mpd.fifo" ]; then
		touch "$HOME/.config/mpd/mpd.fifo"
	fi
}

mpdSessionFiles