#!/usr/bin/env sh

# Find base os i.e. linux,freebsd,darwin,cygwin
os_base () {
  uname -s
}

# Finds linux distro i.e. gentoo,nixos,ubuntu
os_linux_distro () {
  if os_base 'Linux'; then
    linuxDistro=$(cat /etc/*-release 2>/dev/null | \
      grep -m 1 -w -o '\(Arch\|CentOS\|Debian\|Fedora\|Gentoo\|NixOS\|OpenSuse\|Red\ Hat\|SUSE\|Ubuntu\)')
    if [ -z "$linuxDistro"]; then
      linuxDistro=$(uname -a 2>/dev/null | \
        grep -m 1 -w -o '\(Arch\|CentOS\|Debian\|Fedora\|Gentoo\|NixOS\|OpenSuse\|Red\ Hat\|SUSE\|Ubuntu\)')
    fi
  fi
}