#!/usr/bin/env sh

# Add to the path if the DIR doesn't exist
path_add () {

  if [ "$(echo "$PATH" | grep "$1" 2>/dev/null)" = "" ] ; then
    export PATH="${PATH}:$1"
  fi

}

paths_auto () {

  path_add "$HOME/.bin"
  path_add "$HOME/.cabal/bin"
  path_add "$PATH:$GOPATH/bin"

  #export PATH="${PATH}:/usr/bin"
  #export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib64:/usr/lib32"

}