#!/usr/bin/env sh

# Program specific configs

programs_auto () {

  beets_program
  emacs_program
  git_program
  golang_program
  gvim_program
  mpd_program
  nixpkgs_program
  pulseaudio_program
  rtorrent_program
  sublime_text_program
  vim_program

}