#!/usr/bin/env sh

# Program specific configs

apps_headless_configure () {

  program_beets
  program_cabal
  program_emacs
  program_git
  program_golang
  gvim_program
  htop_program
  mpd_program
  nixpkgs_program
  pulseaudio_program
  rtorrent_program
  ssh_program
  tmux_program
  vim_program

}

apps_graphical_configure () {

  sakura_program
  sublime_text_program
  suckless_program
  program_xorg

}
