#!/usr/bin/env sh

rtorrent_path () {

  # Make sure rTorrent is installed
  path_hasbin rtorrent || { echo "'rtorrent' not installed" ; return 1; }
  return 0

}

rtorrent_auto () {

  # if rTorrent isn't installed, be done now
  rtorrent_path || return 1

  # Symlink rTorrent config
  config_ln "rtorrent.rc"

  # Download directories
	if [ ! -d "$HOME/Torrents/Complete" ]; then
	 mkdir -p "$HOME/Torrents/Complete"
  fi
  if [ ! -d "$HOME/Torrents/Incomplete" ]; then
  	mkdir -p "$HOME/Torrents/Incomplete"
  fi
	if [ ! -d "$HOME/Torrents/Watch" ]; then
	  mkdir -p "$HOME/Torrents/Watch"
  fi
  fi
  # Session Directory
  if [ ! -d "$HOME/.local/share/rtorrent" ]; then
	  mkdir -p "$HOME/.local/share/rtorrent"
  fi

}