#!/usr/bin/env sh

rtorrent_path () {

  # Make sure rtorrent is installed
  path_hasbin rtorrent || { echo "No rtorrent installed" ; return 1; }
  return 0

}

rtorrent_auto () {

  # if rtorrent isn't installed, be done now
  rtorrent_path || return 1

  # Symlink rTorrent config
  config_ln rtorrent.rc

  # Download directories
  if [ ! -d "$HOME/Torrents" ]; then
	  mkdir "$HOME/Torrents" || return 1
	  mkdir "$HOME/Torrents/Complete"
	  mkdir "$HOME/Torrents/Incomplete"
	  mkdir "$HOME/Torrents/Watch"
  elif [ -d "$HOME/Torrents" ]; then
	  if [ ! -d "$HOME/Torrents/Complete" ]; then
	    mkdir "$HOME/Torrents/Complete"
  	fi
  	if [ ! -d "$HOME/Torrents/Incomplete" ]; then
  	  mkdir "$HOME/Torrents/Incomplete"
  	fi
	  if [ ! -d "$HOME/Torrents/Watch" ]; then
	    mkdir "$HOME/Torrents/Watch"
  	fi
  fi
  # Session Directory
  if [ ! -d "$HOME/.local/share/rtorrent" ]; then
	  mkdir "$HOME/.local/share/rtorrent"
  fi

}