#!/usr/bin/env sh

# Run an application in the background
run_quiet () {

  # If app isn't installed, be done now
  path_hasbin $1 || return 1

  local PID

  # Check to see if process is already running
  PID=$(pgrep $1)

  # If application is already running, no need to run it
  [ -z "$PID" ] && { $1 >/dev/null 2>&1 ; }

}