#!/usr/bin/env sh

# http://en.wikipedia.org/wiki/Comparison_of_command_shells

shells_configure() { # Run shell configurations

  local SHELL

  for SHELL in ${shellsPreference[@]} ; do
    eval shell_${SHELL}_configure || {
      [ "$?" -eq "2" ] && echo "  ☐ $SHELL"
      [ "$?" -eq "1" ] && echo "  ☒ $SHELL"
      eval shell_${SHELL}_cleanup
      continue
    }
    echo "  ☑ $SHELL"
  done

  return 0

}

shells_theme() { # Setup the theme for the shell

  [ "$(shell_nov)" = "fish" ] && return 0

  # Colors for LS
  case "$(os_kernel)" in
    'linux'|'cygwin')
      eval "$(dircolors -b)"
      alias ls='ls --color=auto'
      ;;
    'freebsd')
      export CLICOLOR=1
      export LSCOLORS="ExGxFxdxCxDhDxaBadaCeC"
      ;;
  esac

  # 256 Colors in the Terminal
  if [ "$TERM" = "xterm" ] || [ "$TERM" = "rxvt-unicode-256color" ] ; then
    export TERM="xterm-256color"
    unset COLORTERM
  fi

  # Setup Special Colors
  if user_root ; then
    NCOLOR="$(prompt_color cyan 0)"
  else
    NCOLOR="$(prompt_color white 1)"
  fi

  if info_ws ; then
    HCOLOR="$(prompt_color green 0)"
  else
    HCOLOR="$(prompt_color red 0)"
  fi

  DCOLOR="$(prompt_color yellow 1)"

}

shells_tmp() { # Create the temporary history file for the shell

  local tmp

  if tmp="$(dir_tmp)" ; then
    export HISTFILE="$TMP/history.$(shell_nov)"
    export SAVEHIST="9999"
  else
    export HISTFILE="/dev/null"
    export SAVEHIST="0"
  fi

}

shells_init() { # Initializes useful functions

  shells_tmp
  #agent_auto

  alias root="sudo_wrap su -"
  alias sprunge="curl -F 'sprunge=<-' http://sprunge.us"
  alias nixpaste="curl -F 'text=<-' http://nixpaste.noip.me"
  alias t='laptop_bat ; date'
  alias sha1="openssl sha1"
  alias sha256="openssl sha256"
  alias sha512="openssl sha512"
  alias youtube="youtube-dl --max-quality --no-check-certificate --prefer-insecure --console-title"
  alias music="ncmpcpp"
  alias tarxz="tar cjvf"
  alias emacs="emacs -nw"
  # Btrfs
  alias defragmentroot="sudo btrfs filesystem defragment -r -v -clzo /"
  alias defragmenthome="sudo btrfs filesystem defragment -r -v /home"
  # Gentoo
  [ "$(os_kernel)" = "linux" ] && [ "$(os_linux)" = "gentoo" ] && {
    alias inst="sudo emerge --ask"
    alias search="emerge --search"
    alias uses="equery uses"
    alias layup="sudo layman -S"
  }
  # Defaults
  export EDITOR="emacs"
  export PAGER="less -r"
  export BLOCKSIZE="K"
  # Locale/UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
  export LESSCHARSET=utf-8
  export PERL_UTF8_LOCALE=1
  export PERL_UNICODE=AS
  # Prevent GUI password dialog
  unset SSH_ASKPASS

  run_quiet mpd

}

shells_preference() {

  local SHELL

  for SHELL in ${shellsPreference[@]} ; do
    path_hasbin "$(tolower $SHELL)" > /dev/null 2>&1 && { echo "$(tolower $SHELL)" ; return 0 ; }
  done

  return 1

}

shells_run() { # Automatically executes the preferred shell

  [ "$(shell_nov)" != "$(shells_preference)" ] && { exec "$(shells_preference)" ; exit $? ; }

}

shells_auto() {

  shells_run
  shells_init
  shells_theme
  prompt_configure

}
