#!/usr/bin/env sh

# http://en.wikipedia.org/wiki/Comparison_of_command_shells

shells_configure () {

  #shell_ash
  shell_bash
  #shell_csh
  #shell_dash
  shell_fish
  #shell_korn
  #shell_pdksh
  #shell_sh
  #shell_tcsh
  shell_zsh

  return 0

}

shells_theme () { # Setup the theme for the shell

  [ "$(shell_nov)" = "fish" ] && return 0

  # Colors for LS
  case "$(os_base)" in

    'linux'|'cygwin')
      eval "$(dircolors -b)"
      alias ls='ls --color=auto'
      ;;

    'freebsd')
      export CLICOLOR=1
      export LSCOLORS="ExGxFxdxCxDhDxaBadaCeC"
      ;;

  esac

  # 256 Colors in the Terminal
  if [ "$TERM" = "xterm" ] || [ "$TERM" = "rxvt-unicode-256color" ] ; then
    export TERM="xterm-256color"
    unset COLORTERM
  fi

  # Setup Special Colors
  if info_root ; then
    NCOLOR="$(prompt_color cyan 0)"
  else
    NCOLOR="$(prompt_color white 1)"
  fi

  if info_ws ; then
    HCOLOR="$(prompt_color green 0)"
  else
    HCOLOR="$(prompt_color red 0)"
  fi

  DCOLOR="$(prompt_color yellow 1)"

}

shells_tmp () { # Create the temporary directory for the shell

  local TMP

  if TMP="$(dir_tmp)" ; then
    export HISTFILE="$TMP/history_$(shell_nov)"
    export SAVEHIST="9999"
  else
    export HISTFILE="/dev/null"
    export SAVEHIST="0"
  fi

}

shells_init () { # Initializes useful functions if the caller is a shell

  shell_tmp
  #agent_auto

  alias root="sudo_wrap su -"
  alias sprunge="curl -F 'sprunge=<-' http://sprunge.us" 
  alias t='laptop_bat ; date'
  alias sha1="openssl sha1"
  alias sha256="openssl sha256"
  alias sha512="openssl sha512"
  alias youtube="youtube-dl --max-quality --no-check-certificate --prefer-insecure --console-title"
  alias music="ncmpcpp"
  alias tarxz="tar cjvf"
  # Btrfs
  alias defragmentroot="sudo btrfs filesystem defragment -r -v -clzo /"
  alias defragmenthome="sudo btrfs filesystem defragment -r -v /home"
  # Gentoo
  alias inst="sudo emerge --ask"
  alias search="emerge --search"
  alias uses="equery uses"
  alias layup="sudo layman -S"
  # Defaults
  export LANGUAGE="en_US:en"
  export EDITOR="vim"
  export PAGER=""
  export BLOCKSIZE="K"


}

shells_preference () {

  local SHELL

  for SHELL in ${shellPreference[@]} ; do

    path_hasbin "$(tolower $SHELL)" > /dev/null 2>&1 && { echo "$(tolower $SHELL)" ; return 0 ; }

  done

  return 1

}

shells_run () { # Automatically executes the preferred shell

  [ "$(shell_nov)" != "$(shells_preference)" ] && { exec "$(shells_preference)" ; exit $? ; }

}

shells_auto () {

  shells_run
  shells_init
  shells_theme
  prompt_configure

}
