#!/usr/bin/env sh

termclr () {

  case "$1" in

    'black')
      [ "$2" -eq "0" ] && echo -n '\e[0;30m' || echo -n '\e[1;30m'
      ;;

    'blue')
      [ "$2" -eq "0" ] && echo -n '\e[0;34m' || echo -n '\e[1;34m'
      ;;

    'cyan')
      [ "$2" -eq "0" ] && echo -n '\e[0;36m' || echo -n '\e[1;36m'
      ;;

    'green')
      [ "$2" -eq "0" ] && echo -n '\e[0;32m' || echo -n '\e[1;32m'
      ;;

    'magenta')
      [ "$2" -eq "0" ] && echo -n '\e[0;35m' || echo -n '\e[1;35m'
      ;;

    'red')
      [ "$2" -eq "0" ] && echo -n '\e[0;31m' || echo -n '\e[1;31m'
      ;;

    'white')
      [ "$2" -eq "0" ] && echo -n '\e[0;37m' || echo -n '\e[1;37m'
      ;;

    'yellow')
      [ "$2" -eq "0" ] && echo -n '\e[0;33m' || echo -n '\e[1;33m'
      ;;

    'underline')
      echo -n '\033[0;4m'
      ;;

    'reset')
      echo -n '\e[0m'
      ;;

    *)
      echo -n '\e[0m'
      ;;

  esac

}
