#!/usr/bin/env sh

# Configuration
volumeMixer="1"
defaultIncrement="5"

vol_path () {

  # Make sure 'pactl' is installed
  path_hasbin pactl || { echo "'pactl' not installed" ; return 1 ; }
  return 0

}

vol_usage () {

  echo "usage: vol [option] [argument]"
  echo
  echo "Options:"
  echo "     up   - increase volume by \`argument'"
  echo "     down - decrease volume by \`argument'"
  echo "     set  - set volume percentage"
  echo "     mute - toggle mute on and off"
  echo "     h, -h, --help - display this message"

}

vol () {

  # If 'pactl' is not installed, be done now
  vol_path || return 1

  # Parse Arguments
  case "$1" in
    '')
      volumeCurrent="doesn't work yet"
      echo "Volume: ${volumeCurrent}"
      ;;
    'up')
      volumeCommand="set-sink-volume"
      if [ -z "$2" ]; then
        volumeModify="+${defaultIncrement}%"
      else
        volumeModify="+${2}%"
      fi
      ;;
    'down')
      volumeCommand="set-sink-volume"
      if [ -z "$2" ]; then
        volumeModify="-${defaultIncrement}%"
      else
        volumeModify="-${2}%"
      fi
      ;;
    'set')
      volumeCommand="set-sink-volume"
      if [ -z "$2" ]; then
        echo "ERROR: 'vol set' requires an argument"
        return 1
      else
        volumeModify="${2}%"
      fi
      ;;
    'mute')
      volumeCommand="set-sink-mute"
      volumeModify="toggle"
      ;;
    '-h'|'--help')
      vol_usage
      return 0
      ;;
    *)
      echo "Unrecognized option \`$1'"
      echo
      vol_usage
      return 1
      ;;
  esac

  # Actual volume change
  pactl ${volumeCommand} ${volumeMixer} ${volumeModify}


}