#!/usr/bin/env sh

# Configuration
volumeMixer="Master"
defaultIncrement="2"

vol_path () {

  # Make sure 'amixer' is installed
  path_hasbin amixer || { echo "'amixer' not installed" ; return 1; }
  return 0

}

vol_usage () {

  echo "usage: vol [option] [argument]"
  echo
  echo "Options:"
  echo "     up   - increase volume by \`argument'"
  echo "     down - decrease volume by \`argument'"
  echo "     set  - set volume percentage"
  echo "     mute - toggle mute on and off"
  echo "     h, -h, --help - display this message"

}

vol () {

  # If 'amixer' is not installed, be done now
  vol_path || return 1

  # Check for input
  if [ -z "$@" ]; then
    echo "ERROR: no input provided"
    vol_usage
    return 1
  fi

  # Parse Arguments
  case "$1" in
    up)
      if [ -z "$2" ]; then
        volumeIncrement="${defaultIncrement}%+"
      else
        volumeIncrement="${2}%+"
      fi
      ;;
    down)
      if [ -z "$2" ]; then
        volumeIncrement="${defaultIncrement}%-"
      else
        volumeIncrement="${2}%-"
      fi
      ;;
    set)
      if [ -z "$2" ]; then
        echo "ERROR: 'vol set' requires an argument"
        return 1
      else
        volumeIncrement="${2}%"
      fi
      ;;
    mute)
      #AMIXARG="toggle"
      echo "doesn't work yet"
      return 1
      ;;
    h|-h|--help)
      vol_usage
      return 0
      ;;
    *)
      echo "Unrecognized option \`$1'"
      echo
      vol_usage
      return 1
      ;;
  esac

  # Actual volume change
  amixer set "$volumeMixer" "${volumeIncrement}"

}