#!/usr/bin/env sh

password_confirmation() {

  local pass1
  local pass2

  while true ; do
    read -s -p "Password: " pass1
    echo
    read -s -p "Confirm: " pass2
    echo
    [ "$pass1" = "$pass2" ] && break
    echo "WARNING: passwords do not match, try again"
  done

  echo "$pass1" > /dev/null 2>&1 && return 0

  return 1

}

y_or_n() { # Ask a yes or no question

  local answer
  local default=2
  local prompt

  case "$2" in
    '')
      default=2
      prompt="(y/n)"
      ;;
    'y')
      default=0
      prompt="(Y/n)"
      ;;
    'n')
      default=1
      prompt="(y/N)"
      ;;
    *)
      default=2
      prompt="(y/n)"
      ;;
  esac

  while true ; do
    read -p "$1 $prompt: " answer

    answer="$(tolower $answer)"

    case "$answer" in
      '')
        [ $default != 2 ] && {
          return $default
        }
        ;;
      'y'|'yes')
        break && return 0
        ;;
      'n'|'no')
        break && return 1
        ;;
    esac

    echo "WARNING: Response must be y/n or yes/no, try again"
  done

  return 2

}
