#!/usr/bin/env sh

password_confirmation() {

  local PASS1
  local PASS2

  while true ; do
    read -s -p "Password: " PASS1
    echo
    read -s -p "Confirm: " PASS2
    echo
    if [ "$PASS1" = "$PASS2" ] ; then
      break
    fi
    echo "WARNING: passwords do not match, try again"
  done

  echo "$PASS1" > /dev/null 2>&1 && return 0

  return 1

}

y_or_n() { # Ask a yes or no question

  local answer
  local default=2
  local prompt

  case "$2" in
    '')
      default=2
      prompt="(y/n)"
      ;;
    'y')
      default=0
      prompt="(Y/n)"
      ;;
    'n')
      default=1
      prompt="(y/N)"
      ;;
    *)
      default=2
      prompt="(y/n)"
      ;;
  esac

  while true ; do
    read -p "$1 $prompt: " answer

    answer="$(tolower $answer)"

    case "$answer" in
      '')
        if [ $default != 2 ] ; then
          return $default
        fi
        ;;
      'y'|'yes')
        break && return 0
        ;;
      'n'|'no')
        break && return 1
        ;;
    esac

    echo "WARNING: Response must be y/n or yes/no, try again"
  done

  return 2

}
