#!/usr/bin/env sh

cpu_architecture() { # Find CPU architecture without endianness

  # http://en.wikipedia.org/wiki/Uname

  # Switch to using Darwin:sysctl Linux:/proc/cpuinfo, uname is part of the kernel and kernel does not guarentee arch

  local architecture

  architecture=$(uname -m | grep -m 1 -w -o "\(\
    arm\|armeb\|armel\|armv5te\|armv6\|armv6l\|armv6t2\|armv7l\|armv8\|\
    i386\|i486\|i686\|i686-AT386\|i86pc\|x86\|x86_32\|i686-64\|x86pc\|x86_64\|amd64\|k1om\|\
    mips\|mips64\|\
    Power Macintosh\|powerpc\|ppc\|ppc64\|\
    sun4u\|sparc\|sparc64\)")

  [ -z "$architecture" ] && { echo "ERROR: failed to detect cpu architecture" ; return 1 ; }

  case "$architecture" in
    'arm'|'armeb'|'armel'|'armv5te'|'armv6'|'armv6l'|'armv6t2'|'armv7l'|'armv8')
      echo "arm"
      ;;
    'mips'|'mips64')
      echo "mips"
      ;;
    'powerpc'|'ppc'|'ppc64')
      echo "ppc"
      ;;
    'sun4u'|'sparc'|'sparc64')
      echo "sparc"
      ;;
    'i386'|'i486'|'i586'|'i686'|'x86'|'x86_32'|'amd64'|'x86_64'|'i686-AT386'|'i86pc'|'i686-64'|'x86pc'|'k1om')
      echo "x86"
      ;;
    *)
      echo "ERROR: invalid cpu architecture '$architecture'"
      return 1
      ;;
  esac

  return 0

}

cpu_endianness() { # Find CPU endianness (ie. 32bit/64bit)

  local endianness
	
  endianness=$(getconf LONG_BIT | grep -m 1 -w -o "\(8\|16\|32\|64\|\128\)" | grep -o '[0-9]*')

  [ -z "$endianness" ] && { echo "ERROR: could not determine cpu endianness" ; return 1 ; }

  echo "$endianness"

  return 0

}

cpu_cores() { # Find number of physical cpu cores

  # Does not work with multiple sockets

  local cpucores

  case $(os_kernel) in
    'linux'|'freebsd')
      cpucores=$(awk '/^cpu\ cores/ { print $4 ; exit }' /proc/cpuinfo | grep -o '[0-9]*')
      ;;
    'darwin')
      cpucores=$(sysctl hw | grep -m 1 "hw.physicalcpu:" | grep -o '[0-9]*')
      ;;
    'cygwin')
      cpucores=$(NUMBER_OF_PROCESSORS | grep -o '[0-9]*')
      ;;
  esac

  [ -z "$cpucores" ] && cpucores="1"

  echo "$cpucores"

  return 0

}

cpu_threads() { # Find number of logical cpu cores

  local cputhreads

  case $(os_kernel) in
    'linux'|'freebsd')
      cputhreads=$(grep -c ^processor /proc/cpuinfo | grep -o '[0-9]*')
      ;;
    'darwin')
      cputhreads=$(sysctl hw | grep -m 1 "hw.logicalcpu:" | grep -o '[0-9]*')
      ;;
    'cygwin')
      cputhreads=""
      ;;
  esac

  [ -z "$cputhreads" ] && cputhreads="$(cpu_cores)"

  echo "$cputhreads"

  return 0

}
