#!/usr/bin/env sh

dotfile_gen() { # Parses the dotfile for variables before generating file

  cat > "$HOME/.$2" < "$DOTFILES_DIR/$1"

}

dotfile_ln() { # Links the configuration file to its proper dotfile

  if [ "$#" -eq "0" ] ; then
  	return 1
  fi

  local dotfile

  for dotfile in "$@" ; do
    symlink "$DOTFILES_DIR/dotfiles/$dotfile" "$HOME/.$dotfile"
  done

}
