#!/usr/bin/env sh

download() { # Find download utility on system

    if path_hasbin "curl" ; then
        curl -O "$@" && return 0
    elif path_hasbin "wget" ; then
        wget "$@" && return 0
    elif path_hasbin "fetch" ; then
        fetch "$@" && return 0
    fi

    echo "ERROR: unable to download file"
    return 1

}
