#!/usr/bin/env sh

exist() { # Check for existence of file or directory

  [ ! -z "$1" ]

  case "$1" in
    '-fc') # Make sure the file exists
      shift
      while [ "$1" ] ; do
        # Make sure file is not a symlink
        if test -L "$1" ; then
          unlink "$1" > /dev/null 2>&1
          [ "$?" == "0" ]
        fi
        # Create file
        if [ ! -f "$1" ] ; then
          touch "$1" > /dev/null 2>&1
          [ "$?" == "0" ]
        fi
        shift
      done

      return 0
      ;;
    '-fx') # Make sure file doesn't exist
      shift
      while [ "$1" ] ; do
        # Make sure file is not a symlink
        if test -L "$1" ; then
          unlink "$1" > /dev/null 2>&1
          [ "$?" == "0" ]
        fi
        # Remove file
        if [ -f "$1" ] ; then
          rm -f "$1" > /dev/null 2>&1
          [ "$?" == "0" ]
        fi
        shift
      done

      return 0
      ;;
    '-dc') # Make sure directory exists
      shift
      while [ "$1" ] ; do
        # Make sure directory is not a symlink
        if test -L "$1" ; then
          unlink "$1" > /dev/null 2>&1
          [ "$?" == "0" ]
        fi
        # Create directory
        if [ ! -d "$1" ] ; then
          mkdir -p "$1" > /dev/null 2>&1
          [ "$?" == "0" ]
        fi
        shift
      done

      return 0
      ;;
    '-dx') # Make sure directory doesn't exists
      shift
      while [ "$1" ] ; do
        # Make sure directory is not a symlink
        if test -L "$1" ; then
          unlink "$1" > /dev/null 2>&1
          [ "$?" == "0" ]
        fi
        # Remove directory
        if [ -d "$1" ] ; then
          rm -rf "$1" > /dev/null 2>&1
          [ "$?" == "0" ]
        fi
        shift
      done

      return 0
      ;;
  esac

  return 1

}
