#!/usr/bin/env sh

file_check () {

  [ -f "$1" ] || {
    echo "Creating file: $1"
    touch "$1" >/dev/null 2>&1
    [ "$?" != "0" ] && return 1
  }

  return 0

}

file_exist () {

  file_check "$1" || { echo "ERROR: failed to create file: $1" ; return 1 ; }

  return 0

}
