#!/usr/bin/env sh

os_kernel() { # Find base os i.e. linux,freebsd,darwin,cygwin

  local kernel

  kernel=$(tolower $(uname -s) | \
  grep -m 1 -w -o '\(cygwin\|darwin\|dragonfly\|freebsd\|linux\|netbsd\|openbsd\)' | \
  head -n 1)

  [ -z "$kernel" ] && { echo "ERROR: not a supported operating system" ; return 1 ; }

  echo "$kernel"

  return 0

}

os_linux() { # Take first result of distro name match

  os_linux_release() { # Finds linux distro via /etc/*-release

    cat $ROOT/etc/*-release 2> /dev/null

  }

  os_linux_uname() { # Finds linux distro via uname -a

    uname -a 2> /dev/null

  }

  os_linux_lsb() { # Find linux distro vix linux standard base

    lsb_release -a 2> /dev/null

  }

  [ "$(os_base)" = "linux" ] || return 1

  local linux

  linux=$(tolower "$(os_linux_distro_release) $(os_linux_distro_uname) $(os_linux_distro_lsb)" | \
  grep -m 1 -w -o '\(arch\|centos\|debian\|fedora\|gentoo\|nixos\|opensuse\|red\ hat\|suse\|ubuntu\)' | \
  head -n 1)

  [ -z "$linuxDISTRO" ] && { echo "ERROR: not a supported linux operating system" ; return 1 ; }

  echo "$linuxDISTRO"

  return 0

}
