#!/usr/bin/env sh

password_confirmation() {

  local PASS1
  local PASS2

  while true ; do
    read -s -p "Password: " PASS1
    echo
    read -s -p "Confirm: " PASS2
    echo
    [ "$PASS1" = "$PASS2" ] && break
    echo "WARNING: passwords do not match, try again"
  done

  echo "$PASS1" > /dev/null 2>&1 && return 0

  return 1

}
