#!/usr/bin/env sh

path_add() { # Add direcory to $PATH

  [ "$(echo "$PATH" | grep "$1" 2> /dev/null)" = '' ] && {
    export PATH="${PATH}:$1"
  }

}

path_remove()  { # Remove directory from $PATH

  [ "$(echo "$PATH" | grep "$1" 2> /dev/null)" = '' ] || {
    export PATH=`echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`
  }

}

path_bin() { # Finds the path to the binary

  [ "$#" -ne "1" ] && return 2

  path_hasbin "$1" > /dev/null 2>&1 && type "$1" | awk '{print $3}' && return 0

  return 1

}
