#!/usr/bin/env sh

symlink () { # Make sure the symbolic link points to the correct location $2 -> $1

  mkdir -p "$(dirname "$2")"
  if [ "$(readlink -f "$2")" != "$1" ] ; then
    rm -rf "$2"
    if [ -f "$1" ] || [ -d "$1" ] ; then
      ln -s "$1" "$2" 2>/dev/null || return 1
    else
      return 1
    fi
  fi

}
