#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# If not running as login don't do the rest
shopt -q login_shell || return

# Load the configuration options
. "$(readlink -f $(dirname $(readlink -f ~/.bashrc))/../)/lib/loader"
agent_auto
shell_best $@
shell_init
shell_theme

# Load the local config
[ -f "$HOME/.bashrc.local" ] && . "$HOME/.bashrc.local"
