#!/usr/bin/env sh

# Run local commands first
[ -f "$HOME/.xinitrc.local" ] && . $HOME/.xinitrc.local

# Import the modules automatically
. "$(readlink -f $(dirname $(readlink -f $HOME/.xinitrc))/../)/lib/loader"
path_add "$HOME/.bin"
agent_auto
graphical_autorun $@
