#!/usr/bin/env zsh
. "$(readlink -f $(dirname $(readlink -f $HOME/.zshrc))/../)/lib/loader"
shell_best $@
shell_init

# Path to your oh-my-zsh configuration.
ZSH="$(dir_conf)/lib/oh-my-zsh"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="takashiyoshida"
#ZSH_THEME="mh"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="false"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(battery svn git screen extract encode64 task urltools pass)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
shell_theme
alias sudo="nocorrect sudo"
[ -f "$HOME/.zshrc.local" ] && source $HOME/.zshrc.local
