#!/usr/bin/env sh

rtorrent_program () {

  path_hasbin "rtorrent" || return 1

	dir_exist "$HOME/Torrents/Complete" || return 1
  dir_exist "$HOME/Torrents/Incomplete" || return 1
	dir_exist "$HOME/Torrents/Watch" || return 1
  dir_exist "$HOME/.local/share/rtorrent" || return 1

  config_ln "rtorrent.rc"

}
