#!/usr/bin/env bash

# This file is part of Kratos.
# Copyright (c) 2014-2015, Cody Opel <codyopel@gmail.com>.
#
# Use of this source code is governed by the terms of the
# BSD-3 license.  A copy of the license can be found in
# the `LICENSE' file in the top level source directory.

# Test for a login shell
shopt -q login_shell || return

. "$(readlink -f $(dirname $(readlink -f $HOME/.kshrc))/../)/login-shell.sh"

# Load the local config
if [ -f "$HOME/.bash_login.local" ] ; then
  . "$HOME/.bash_login.local"
fi

if [[ $- == *i* ]] ; then
  . "$HOME/.bashrc"
fi
