#!/usr/bin/env sh

# xinitrc start deskenv

# Run xsession after for deskenvs that don't support doing so

# Run local commands first
[[ -f "${HOME}/.xinitrc.local" ]] && . "${HOME}/.xinitrc.local"

# Gnome 3.xx
#exec gnome-session
#systemd --user
#dbus-launch nm-applet &
#eval &(gnome-keyring-daemon --components=pkcs11,secrets,ssh,gpg)
#export GNOME_KEYRING_PID
#export GNOME_KEYRING_SOCKET
#export SSH_AUTH_SOCK
#export GPG_AGENT_INFO

if [[ -f "${HOME}/.xsession" ]] ; then
  . "${HOME}/.xsession"
fi
