#!/usr/bin/env zsh

# This file is part of Kratos.
# Copyright (c) 2014-2015, Cody Opel <codyopel@gmail.com>.
#
# Use of this source code is governed by the terms of the
# BSD-3 license.  A copy of the license can be found in
# the `LICENSE' file in the top level source directory.

# Test for a login shell
[[ -o login ]] || return

. "$(readlink -f $(dirname $(readlink -f ${HOME}/.zprofile))/../)/init/shell.login.sh"

# Load the local config
if [ -f "${HOME}/.bash_login.local" ] ; then
  . "${HOME}/.bash_login.local"
fi

if [[ -o interactive ]] ; then
  . "${HOME}/.zshrc"
fi
