#!/usr/bin/env zsh

# This file is part of Kratos.
# Copyright (c) 2014-2015, Cody Opel <codyopel@gmail.com>.
#
# Use of this source code is governed by the terms of the
# BSD-3 license.  A copy of the license can be found in
# the `LICENSE' file in the top level source directory.

# Test for a login shell
[[ -o login ]] || return

export KRATOS_IS_LOGIN_SHELL=true
exec zsh --interactive
exit $?
