#!/usr/bin/env bash

# This file is part of Kratos.
# Copyright (c) 2014-2016, Cody Opel <codyopel@gmail.com>.
#
# Use of this source code is governed by the terms of the
# BSD-3 license.  A copy of the license can be found in
# the `LICENSE' file in the top level source directory.

[[ -o interactive ]] || return

# Prevent attempts to spawn bash if it doesn't exist, this makes
# accessing a shell from the user's account impossible.
if type bash > /dev/null ; then
  exec bash -i
  exit $?
fi
