#!/usr/bin/env zsh

# This file is part of Kratos.
# Copyright (c) 2014-2015, Cody Opel <codyopel@gmail.com>.
#
# Use of this source code is governed by the terms of the
# BSD-3 license.  A copy of the license can be found in
# the `LICENSE' file in the top level source directory.

[[ -o interactive ]] || return

# FIXME
alias ebuild='nocorrect ebuild'
alias gist='nocorrect gist'
alias heroku='nocorrect heroku'
alias hpodder='nocorrect hpodder'
alias man='nocorrect man'
alias mkdir='nocorrect mkdir'
alias mv='nocorrect mv'
alias mysql='nocorrect mysql'
alias sudo='nocorrect sudo'

# Load shell configuration loader
. "$(readlink -f $(dirname $(readlink -f ${HOME}/.zshrc))/../)/init/init.zsh"

# Load the local config
if [[ -f "${HOME}/.zshrc.local" ]] ; then
  source "${HOME}/.zshrc.local"
fi
