#!/usr/bin/env sh

app_beets_installed () {

  path_hasbin "beet" || return 1

  return 0

}

app_beets_dirs () {

  dir_exist "$XDG_CONFIG_HOME/beets" || return 1

  return 0

}

app_beets_dotfiles () {

(
cat <<'BEETSDOTFILE'
color: yes
original_year: yes
per_disc_numbering: no
write: yes
import:
    move: yes
    resume: yes
paths:
    default: ${artist}/${original_year} - $album%aunique{}/${artist}_${original_year}_${artist}_${track}_${title}_${channels}.${bitdepth}.${samplerate}
    singleton: ${artist}/${original_year} - $album%aunique{} [single]/${artist}_${original_year}_${artist}_${track}_${title}_${channels}.${bitdepth}.${samplerate}
    comp: COMPILATIONS/$album%aunique{}/$album_$track_$title_${channels}.${bitdepth}.${samplerate}
    soundtrack: SOUNDTRACKS/$album/$album_$track_$title_${channels}.${bitdepth}.${samplerate}

BEETSDOTFILE
) > "$XDG_CONFIG_HOME/beets/config.yaml" || return 1

  return 0

}

app_beets_cleanup () {

  rm -rf "$XDG_CONFIG_HOME/beets"

}

app_beets_configure () {

  app_beets_installed || return 1

  app_beets_dirs || return 1

  app_beets_dotfiles || return 1

  return 0

}

app_beets () {

  local APP

  APP="beets"

  eval app_${APP}_configure || {

    eval app_${APP}_cleanup

    [ "$?" -eq "2" ] && { echo "  ☐ $APP" ; return 1 ; }
    [ "$?" -eq "1" ] && { echo "  ☒ $APP" ; return 1 ; }

  }

  echo "  ☑ $APP"

  return 0

}
