#!/usr/bin/env sh

app_beets_installed () {

  path_hasbin "beet" || return 1

  return 0

}

app_beets_dirs () {

  dir_exist "$XDG_CONFIG_HOME/beets" || return 1

  return 0

}

app_beets_dotfiles () {

  config_ln "config/beets/config.yaml" || return 1

  return 0

}

app_beets_cleanup () {

  rm -rf "$XDG_CONFIG_HOME/beets"

}

app_beets_configure () {

  app_beets_installed || return 1

  app_beets_dirs || return 1

  app_beets_dotfiles || return 1

  return 0

}

app_beets () {

  app_beets_configure || { app_beets_cleanup ; return 1 ; }

  return 0

}
