#!/usr/bin/env sh

app_cabal_installed () {

  path_hasbin "cabal" > /dev/null || return 1

  return 0

}

app_cabal_dirs () {

  dir_exist "$HOME/.cabal/bin" || return 1

  return 0

}

app_cabal_paths () {

  path_add "$HOME/.cabal/bin" || return 1

  return 0

}

app_cabal_configure () {

  app_cabal_installed || return 2

  app_cabal_dirs || return 1

  app_cabal_paths || return 1

  return 0

}

app_cabal_cleanup () {

  rm -rf "$HOME/.cabal"

}

app_cabal () {

  local APP

  APP="cabal"

  eval app_${APP}_configure || {

    [ "$?" -eq "2" ] && { echo "  ☐ $APP" ; }
    [ "$?" -eq "1" ] && { echo "  ☒ $APP" ; }

    eval app_${APP}_cleanup

    return 1

  }

  echo "  ☑ $APP"

  return 0

}
