#!/usr/bin/env sh

app_emacs_installed () {

  path_hasbin "emacs"  || return 1

  return 0

}

app_emacs_dotfiles () {

  config_ln "emacs.d" || return 1

  return 0

}

app_emacs_cleanup () {

  rm -f "$HOME/.emacs.d"

}

app_emacs_configure () {

  app_emacs_installed || return 2

  [ -d "$HOME/.emacs" ] && { rm -rf "$HOME/.emacs" ; }

  app_emacs_dotfiles || return 1

  return 0

}

app_emacs () {

  local APP

  APP="emacs"

  eval app_${APP}_configure || {

    [ "$?" -eq "2" ] && { echo "  ☐ $APP" ; }
    [ "$?" -eq "1" ] && { echo "  ☒ $APP" ; }

    eval app_${APP}_cleanup

    return 1

  }

  echo "  ☑ $APP"

  return 0

}
