#!/usr/bin/env sh

app_emacs_installed () {

  path_hasbin "emacs"  || return 1

  return 0

}

app_emacs_dotfiles () {

  config_ln "emacs.d" || return 1

  return 0

}

app_emacs_cleanup () {

  rm -f "$HOME/.emacs.d"

}

app_emacs_configure () {

  app_emacs_installed || return 1

  [ -d "$HOME/.emacs" ] && { rm -rf "$HOME/.emacs" ; }

  app_emacs_dotfiles || return 1

  return 0

}

app_emacs () {

  app_emacs_configure || { app_emacs_cleanup ; return 1 ; }

  echo "  ✓ emacs"

  return 0

}
