#!/usr/bin/env sh

app_git_installed () {

  path_hasbin "git" || return 1

  return 0

}

app_git_dotfiles () {

  [ -f "$HOME/.gitconfig" ] && { rm -f "$HOME/.gitconfig" ; }

(
cat <<GITCONFIG
[user]
    email = $emailGit
    name = $usernameGit
[push]
    default = simple

GITCONFIG
) > "$HOME/.gitconfig"

  return 0

}

app_git_configure () {

  app_git_installed || return 2

  app_git_dotfiles || return 1

  return 0

}

app_git () {

  local APP

  APP="git"

  eval app_${APP}_configure || {

    [ "$?" -eq "2" ] && { echo "  ☐ $APP" ; }
    [ "$?" -eq "1" ] && { echo "  ☒ $APP" ; }

    return 1

  }

  echo "  ☑ $APP"

  return 0

}
