#!/usr/bin/env sh

app_gvim_installed () {

  path_hasbin "gvim" > /dev/null || return 1

  return 0

}

app_gvim_dotfiles () {

  config_ln "gvimrc" || return 1

  return 0

}

app_gvim_cleanup () {

  rm -f "$HOME/.gvimrc"

}

app_gvim_configure () {

  app_gvim_installed || return 2

  app_gvim_dotfiles || return 1

  return 0

}

app_gvim () {

  local APP

  APP="gvim"

  eval app_${APP}_configure || {

    [ "$?" -eq "2" ] && { echo "  ☐ $APP" ; }
    [ "$?" -eq "1" ] && { echo "  ☒ $APP" ; }

    eval app_${APP}_cleanup

    return 1

  }

  echo "  ☑ $APP"

  return 0

}
