#!/usr/bin/env sh

app_htop_installed () {

  path_hasbin "htop" || return 1

  return 0

}

app_htop_dirs () {

  dir_exist "$XDG_CONFIG_HOME/htop" || return 1

  return 0

}

app_htop_dotfiles () {

  config_ln "config/htop/htoprc" || return 1

  return 0

}

app_htop_cleanup () {

  rm -rf "$XDG_CONFIG_HOME/htop"

}

app_htop () {

  app_htop_installed  || return 1

  app_htop_dirs || return 1

  app_htop_dotfiles || return 1

  return 0

}

app_htop () {

  app_htop_configure || { app_htop_cleanup ; return 1 ; }

  return 0

}
