#!/usr/bin/env sh

program_mpd_installed () {

  path_hasbin "mpd" || return 1

  return 0

}

mpd_program () {

  program_mpd_installed || return 1

  dir_exist "$XDG_CONFIG_HOME/mpd/playlists" || return 1

  file_exist "$XDG_CONFIG_HOME/mpd/database" || return 1
  file_exist "$XDG_CONFIG_HOME/mpd/pid" || return 1
  file_exist "$XDG_CONFIG_HOME/mpd/state" || return 1
  file_exist "$XDG_CONFIG_HOME/mpd/sticker.sql" || return 1
  file_exist "$XDG_CONFIG_HOME/mpd/log" || return 1

  config_ln "config/mpd/mpd.conf" || return 1

  return 0

}
