#!/usr/bin/env sh

app_ncmpcpp_installed () {

  path_hasbin "ncmpcpp" || return 1

  return 0

}

app_ncmpcpp_dirs () {

  dir_exist "$HOME/.ncmpcpp" || return 1

  return 0

}

app_ncmpcpp_dotfiles () {

  config_ln "ncmpcpp/config" || return 1

  return 0

}

app_ncmpcpp_cleanup () {

  rm -rf "$HOME/.ncmpcpp"

}

app_ncmpcpp_configure () {

  app_mpd_installed || return 1
  app_ncmpcpp_installed || return 1

  app_ncmpcpp_dirs || return 1

  app_ncmpcpp_dotfiles || return 1

  return 0

}

app_ncmpcpp () {

  app_ncmpcpp_configure || { app_ncmpcpp_cleanup ; return 1 ; }

  return 0

}