#!/usr/bin/env sh

app_ncmpcpp_installed () {

  path_hasbin "ncmpcpp" || return 1

  return 0

}

app_ncmpcpp () {

  app_mpd_installed || return 1
  app_ncmpcpp_installed || return 1

  dir_exist "$HOME/.ncmpcpp" || return 1

  config_ln "ncmpcpp/config"

}