#!/usr/bin/env sh

app_nixpkgs_installed () {

  path_hasbin "nix-env" || return 1

  return 0

}

app_nixpkgs_dirs () {

  dir_exist "$HOME/.nixpkgs" || return 1

  return 0

}

app_nixpkgs_dotfiles () {

  config_ln "nixpkgs/config.nix" || return 1

  return 0

}

app_nixpkgs_cleanup () {

  rm -rf "$HOME/.nixpkgs"

}

app_nixpkgs_configure () {

  app_nixpkgs_installed || return 1

  app_nixpkgs_dirs || return 1

  app_nixpkgs_dotfiles || return 1

  return 0

}

app_nixpkgs () {

  app_nixpkgs_configure || { app_nixpkgs_cleanup ; return 1 ; }

  echo "nixpkgs"

  return 0

}
