#!/usr/bin/env sh

app_nixenv_installed () {

  path_hasbin "nix-env" || return 1

  return 0

}

app_nixpkgs () {

  app_nixenv_installed || return 1

  config_ln "nixpkgs" || return 1

  return 0

}
