#!/usr/bin/env sh

app_rtorrent_installed () {

  path_hasbin "rtorrent" || return 1

  return 0

}

app_rtorrent () {

  app_rtorrent_installed || return 1

  dir_exist "$HOME/Torrents/Complete" || return 1
  dir_exist "$HOME/Torrents/Incomplete" || return 1
  dir_exist "$HOME/Torrents/Watch" || return 1
  dir_exist "$XDG_DATA_HOME/rtorrent" || return 1

  config_ln "rtorrent.rc"

}
