#!/usr/bin/env sh

app_sublime_installed () {

  path_hasbin "sublime" > /dev/null || return 1

  return 0

}

app_sublimetext () {

  app_sublime_installed || return 2

  config_ln "config/sublime-text-3"

  echo "  ✓ sublimetext"

  return 0

}
