#!/usr/bin/env sh

app_suckless_installed () {

  path_hasbin "st" || return 1

  return 0

}

app_suckless () {

  app_nixpkgs || return 1
  app_suckless_installed || return 1

  local OLD

  OLD="$(pwd)"

  [ -d "$(dir_conf)/dotfiles/nixpkgs/st/" ] && {
    cd "$(dir_conf)/dotfiles/nixpkgs/st/"
    if [ -f "config.$(hostname).h" ] ; then
      symlink "config.$(hostname).h" "config.mach.h"
    else
      symlink "config.other.h" "config.mach.h"
    fi
    cd "$OLD"
  }

}
