#!/usr/bin/env sh

app_tmux_installed () {

  path_hasbin "tmux" || return 1

  return 0

}

app_tmux_dotfiles () {

  config_ln "tmux.conf" || return 1

  return 0

}

app_tmux_cleanup () {

  rm -f "$HOME/tmux.conf"

}

app_tmux_configure () {

  app_tmux_installed || return 1

  app_tmux_dotfiles || return 1

  return 0

}

app_tmux () {

  local APP

  APP="tmux"

  eval app_${APP}_configure || {

    eval app_${APP}_cleanup

    [ "$?" -eq "2" ] && { echo "  ☐ $APP" ; return 1 ; }
    [ "$?" -eq "1" ] && { echo "  ☒ $APP" ; return 1 ; }

  }

  echo "  ☑ $APP"

  return 0

}
