#!/usr/bin/env sh

app_vim_installed () {

  path_hasbin "vim" || return 1

  return 0

}

app_vim () {

  app_vim_installed || return 1

  [ -d "$HOME/.viminfo" ] && { rm -rf "$HOME/.viminfo" ; return $? ; }

  config_ln "vimrc"

}
