#!/usr/bin/env sh

app_xorg_installed () {

  path_hasbin "Xorg" || return 1

  return 0

}

app_xorg_dotfiles () {

  config_ln "xinitrc" "xprofile" "xsession" || return 1 #"Xresources"

  return 0

}

app_xorg_cleanup () {

  rm -f "$HOME/.xinitrc"
  rm -f "$HOME/.xprofile"
  rm -f "$HOME/.xsession"
  rm -f "$HOME/.Xresources"

}

app_xorg_configure () {

  app_xorg_installed || return 1

  app_xorg_dotfiles || return 1

  return 0

}

app_xorg () {

  app_xorg_configure || { app_xorg_cleanup ; return 1 ; }

  return 0

}
