#!/usr/bin/env sh

app_xorg_installed () {

  path_hasbin "Xorg" > /dev/null || return 1

  return 0

}

app_xorg_dotfiles () {

  [ -f "$HOME/.xinitrc" ] && { rm -f "$HOME/.xinitrc" ; }
  [ -f "$HOME/.xprofile" ] && { rm -f "$HOME/.xprofile" ; }
  [ -f "$HOME/.xsession" ] && { rm -f "$HOME/.xsession" ; }
  [ -f "$HOME/.Xresources" ] && { rm -f "$HOME/.Xresources" ; }

(
cat <<XINITRC
#!/usr/bin/env sh

# Run local commands first
[ -f "$HOME/.xinitrc.local" ] && . "$HOME/.xinitrc.local"

. "$DOTFILES_DIR/lib/loader"

[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

path_add "$HOME/.bin"
#agent_auto
deskenv_run

# Gnome 3.xx
#exec gnome-session
#systemd --user
#dbus-launch nm-applet &
#eval &(gnome-keyring-daemon --components=pkcs11,secrets,ssh,gpg)
#export GNOME_KEYRING_PID
#export GNOME_KEYRING_SOCKET
#export SSH_AUTH_SOCK
#export GPG_AGENT_INFO

XINITRC
) > "$HOME/.xinitrc" || return 1

(
cat <<XPROFILE
#!/usr/bin/env sh

# Run local commands first
[ -f "$HOME/.xprofile.local" ] && . "$HOME/.xprofile.local"

. "$DOTFILES_DIR/lib/loader"

XPROFILE
) > "$HOME/.xprofile" || return 1

symlink "$HOME/.xinitrc" "$HOME/.xsession" || return 1


  return 0

}

app_xorg_cleanup () {

  [ -f "$HOME/.xinitrc" ] && { rm -f "$HOME/.xinitrc" ; }
  [ -f "$HOME/.xprofile" ] && { rm -f "$HOME/.xprofile" ; }
  [ -f "$HOME/.xsession" ] && { rm -f "$HOME/.xsession" ; }
  [ -f "$HOME/.Xresources" ] && { rm -f "$HOME/.Xresources" ; }

}

app_xorg_configure () {

  app_xorg_installed || return 2

  app_xorg_dotfiles || return 1

  return 0

}

app_xorg () {

  local APP

  APP="xorg"

  eval app_${APP}_configure || {

    [ "$?" -eq "2" ] && { echo "  ☐ $APP" ; }
    [ "$?" -eq "1" ] && { echo "  ☒ $APP" ; }

    eval app_${APP}_cleanup

    return 1

  }

  echo "  ☑ $APP"

  return 0

}
