#!/usr/bin/env sh

# https://www.gentoo.org/proj/en/gentoo-alt/prefix/
# http://wiki.gentoo.org/wiki/Prefix/libc
# http://wiki.gentoo.org/wiki/OpenRC/Prefix
# http://en.wikipedia.org/wiki/Gentoo/Alt
# http://www.funtoo.org/Gentoo_Prefix_On_Mac_OS_X
# https://gist.github.com/ypresto/2145498
# https://github.com/npinto/gentoo-prefix-bootstrap
# https://blog.jolexa.net/category/linux/gentoo/gentoo-prefix/