#!/usr/bin/env sh

# Enforces that an application is installed
require_app () {
  which "$1" >/dev/null 2>&1
  if [ "$?" -ne "0" ]; then
    echo "Requires: $1" >&2
    exit 2
  fi
}
require_all () {
  require_app git
  require_app gpg
  require_app openssl
}

# Hash the given Commit
hash_commit () {
  git archive "$1" | openssl dgst -sha512 -binary
}
