#!/usr/bin/env sh

require_app () { # Enforces that an application is installed

  which "$1" >/dev/null 2>&1
  if [ "$?" -ne "0" ] ; then
    echo "ERROR: required dependency '$1' is not installed" >&2
    exit 2
  fi

}

require_all () {

  require_app git
  require_app gpg
  require_app openssl

}

hash_commit () { # Hash the given Commit

  git archive "$1" | openssl dgst -sha512 -binary

}
