#!/usr/bin/env sh

test_ws_valid () {
  hostname () {
    echo "wl"
  }
  info_ws
  test_eq "0" "$?"
}
test_register test_ws_valid

test_ws_invalid () {
  hostname () {
    echo "wl2"
  }
  info_ws
  test_eq "1" "$?"
  hostname () {
    echo "nas"
  }
  info_ws
  test_eq "1" "$?"
}
test_register test_ws_valid

test_info_root () {
  if [ "$(id -u)" -ne "0" ]; then
    USER=root
    info_root
    test_eq "1" "$?"
  else
    USER=nobody
    info_root
    test_eq "0" "$?"
  fi
}
test_register test_info_root
