#!/usr/bin/env sh

test_loader_shell () {
  [ "$(shell)" = "$RUNNING_SHELL" ]
}
test_register test_loader_shell

test_array_empty () {
  array_new ARR || return 1
  array_empty ARR || return 1
  array_append ARR "Hello"
  array_empty ARR && return 1
  array_new ARR
  array_new ARR || return 1
}
test_register test_array_empty

test_array_forall_empty () {
  array_new ARR
  OUT="$(array_forall ARR echo 2>&1)" || return 1
  test_seq "" "$OUT"
}
test_register test_array_forall_empty

test_array_forall_success () {
  array_new ARR
  array_append ARR "Hello"
  array_append ARR " "
  array_append ARR "World"

  tfun () {
    printf "%s" "$1"
    return 0
  }
  FALL="$(array_forall ARR tfun 2>&1)" || return 1
  test_seq "Hello World" "$FALL"
}
test_register test_array_forall_success

test_array_forall_efail () {
  array_new ARR
  array_append ARR "1"
  array_append ARR "2"
  array_append ARR "3"
  array_append ARR "4"

  tfun () {
    printf "%s" "$1"
    [ "$1" -ne "3" ]
  }
  FAIL="$(array_forall ARR tfun 2>&1)" && return 1
  test_seq "123" "$FAIL"
}
test_register test_array_forall_efail

test_dir_conf () {
  [ "$(readlink -f ..)" = "$(dir_conf)" ]
}
test_register test_dir_conf
