#!/usr/bin/env sh

# https://www.gentoo.org/proj/en/gentoo-alt/prefix/
# http://wiki.gentoo.org/wiki/Prefix/libc
# http://wiki.gentoo.org/wiki/OpenRC/Prefix
# http://en.wikipedia.org/wiki/Gentoo/Alt
# http://www.funtoo.org/Gentoo_Prefix_On_Mac_OS_X
# https://gist.github.com/ypresto/2145498
# https://github.com/npinto/gentoo-prefix-bootstrap
# https://blog.jolexa.net/category/linux/gentoo/gentoo-prefix/

gentoo () {

cat <<EOF
$(termclr magenta)                                             .
$(termclr magenta)       .vir.                                d&b
$(termclr magenta)    .d&&&&&&b.    .cd&&b.     .d&&b.   d&&&&&&&&&&&b  .d&&b.      .d&&b.
$(termclr magenta)    &&&&( )&&&b d&&&()&&&.   d&&&&&&&b Q&&&&&&&P&&&P.&&&&&&&b.  .&&&&&&&b.
$(termclr magenta)    Q&&&&&&&&&&B&&&&&&&&P"  d&&&PQ&&&&b.   &&&&.   .&&&P' '&&& .&&&P' '&&&
$(termclr magenta)      "&&&&&&&P Q&&&&&&&b  d&&&P   Q&&&&b  &&&&b   &&&&b..d&&& &&&&b..d&&&
$(termclr magenta)     d&&&&&&P"   "&&&&&&&& Q&&&     Q&&&&  &&&&&   'Q&&&&&&&P  'Q&&&&&&&P
$(termclr magenta)    &&&&&&&P       '"""""   ""        ""   Q&&&P     "Q&&&P"     "Q&&&P"
$(termclr magenta)    'Q&&P"                                  """

$(termclr white 1)                           Gentoo prefix installer

$(termclr white 1)                   Author: Cody Opel <codyopel@gmail.com>


Options:
  [1] Install
  [2] Re-Install
$(termclr reset)
EOF

}

bootstrap_bash () {

[ -z "$1" ] && exit -1

mkdir -p "$1"
cd "$1"
mkdir bash-build
cd bash-build

GENTOO_MIRRORS=${GENTOO_MIRRORS:="http://gentoo.mirrors.pair.com/distfiles"}

ftp "${GENTOO_MIRRORS}/bash-4.1.tar.gz"
gzip -d bash-4.1.tar.gz
tar -xf bash-4.1.tar
cd bash-4.1

./configure --prefix="${1}"/usr --disable-nls
make
make install

}