#!/usr/bin/env sh

shell_bash_installed() {

  path_hasbin "bash" || return 1

  return 0

}

shell_bash_dotfiles() {

  exist -fx "$HOME/.bashrc" "$HOME/.bash_logout" "$HOME/.bash_profile"

  dotfile_ln "bashrc"

  return 0

}

shell_bash_cleanup() {

  exist -fx "$HOME/.bashrc" "$HOME/.bash_logout" "$HOME/.bash_profile"

}

shell_bash_configure() {

  shell_bash_installed || return 1

  shell_bash_dotfiles || return 1

}
