#!/usr/bin/env sh

shell_zsh_installed() {

  path_hasbin "zsh" || return 1

  return 0

}

shell_zsh_dotfiles() {

  exist -fx "$HOME/.zshrc" "$HOME/.zlogout" "$HOME/.zprofile"

(
cat <<ZSHRC
#!/usr/bin/env zsh

# Allow for functions in the prompt
setopt PROMPT_SUBST

# Set to this to use case-sensitive completion
CASE_SENSITIVE="false"

DISABLE_AUTO_UPDATE="true"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
COMPLETION_WAITING_DOTS="true"

alias sudo="nocorrect sudo"

# Load shell configuration options
. "$DOTFILES_DIR/lib/loader"
shells_auto

# Load the local config
[ -f "$HOME/.zshrc.local" ] && source $HOME/.zshrc.local

ZSHRC
) > "$HOME/.zshrc" || return 1

(
cat <<ZLOGOUT
#!/usr/bin/env zsh

ZLOGOUT
) > "$HOME/.zlogout" || return 1

(
cat <<ZPROFILE
#!/usr/bin/env zsh

ZPROFILE
) > "$HOME/.zprofile" || return 1

}

shell_zsh_cleanup() {

  exist -fx "$HOME/.zshrc" "$HOME/.zlogout" "$HOME/.zprofile"

}

shell_zsh_configure() {

  shell_zsh_installed || return 2

  shell_zsh_dotfiles || return 1

  return 0

}
