#!/usr/bin/env sh

awesome_deskenv () {

  path_hasbin "awesome" || return 1

  TILING=1


  [ -d "$HOME/.config/wallpaper" ] && {
    [ "$(ls "$HOME/.config/wallpaper" | wc -l)" -gt "1" ] && {
      sleep 2
      while true ; do
        awsetbg -r "$HOME/.config/wallpaper"
        sleep 300
      done &
    }
  }

  config_ln "config/awesome"

}
