#!/usr/bin/env sh

awesome_deskenv () {

  path_hasbin "awesome" || return 1

  TILING=1


  [ -d "$XDG_CONFIG_HOME/wallpaper" ] && {
    [ "$(ls "$XDG_CONFIG_HOME/wallpaper" | wc -l)" -gt "1" ] && {
      sleep 2
      while true ; do
        awsetbg -r "$XDG_CONFIG_HOME/wallpaper"
        sleep 300
      done &
    }
  }

  config_ln "config/awesome"

}
