#!/usr/bin/env sh

deskenv_cinnamon_installed () {

  path_hasbin "cinnamon-session" > /dev/null || return 1

  return 0

}

deskenv_cinnamon () {

  deskenv_cinnamon_installed || return 1

  echo "  ✓ cinnamon"

  return 0

}
