#!/usr/bin/env sh

deskenv_gnome_installed () {

  path_hasbin "gnome-session" > /dev/null || return 1

  return 0

}

deskenv_gnome_cleanup () {

  return 0

}

deskenv_gnome_configure () {

  deskenv_gnome_installed || return 1

  echo "  ✓ gnome"

  return 0

}
