#!/usr/bin/env sh

deskenv_i3_installed () {

  path_hasbin "i3" > /dev/null || return 1

  return 0

}

deskenv_i3_cleanup () {

  return 0

}

deskenv_i3_configure () {

  deskenv_i3_installed || return 1

  echo "  ✓ i3"

  return 0

}
