#!/usr/bin/env sh

xfce4_deskenv () {

  path_hasbin "startxfce4" || return 1

  # Should be move to program specific
  symlink "$XDG_CONFIG_HOME/Terminal" "$XDG_CONFIG_HOME/xfce4/terminal"

  # TODO: xfce theme

  # TODO: whisker menu

}
