#!/usr/bin/env sh

deskenv_xfce_installed () {

  path_hasbin "startxfce4" || return 1

  return 0

}

deskenv_xfce () {

  deskenv_xfce_installed || return 1

  # Should be move to program specific
  symlink "$XDG_CONFIG_HOME/Terminal" "$XDG_CONFIG_HOME/xfce4/terminal"

  # TODO: xfce theme

  # TODO: whisker menu

}
