#!/usr/bin/env sh

xfce4_deskenv () {

  path_hasbin "startxfce4" || return 1

  # Should be move to program specific
  symlink "$HOME/.config/Terminal" "$HOME/.config/xfce4/terminal"

  # TODO: xfce theme

  # TODO: whisker menu

}