#!/usr/bin/env sh

deskenv_xmonad_installed () {

  path_hasbin "xmonad" || return 1

  return 0

}

xmonad_deskenv () {

  deskenv_xmonad_installed || return 1

  TILING=1

  #dir_exist "$HOME/.xmonad" || return 1

  #config_ln "xmonad/xmonad.hs"
  config_ln "xmonad"

}
